### ISSUE TITLE
Raspbian error python

### ISSUE THREAD

**Issue by elRadix** [linuxserver/docker-medusa#22]
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch

Python errors , how can this be resolved ?

```
> GID/UID
> -------------------------------------
> 
> User uid:    0
> User gid:    0
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing... 
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> Traceback (most recent call last):
>   File "/app/medusa/start.py", line 8, in <module>
>     from medusa.__main__ import main
>   File "/app/medusa/medusa/__init__.py", line 20, in <module>
>     from medusa.app import app
>   File "/app/medusa/medusa/app.py", line 8, in <module>
>     from threading import Lock
>   File "/usr/lib/python2.7/threading.py", line 13, in <module>
>     from collections import deque as _deque
>   File "/usr/lib/python2.7/collections.py", line 20, in <module>
>     from _collections import deque, defaultdict
> ImportError: Error loading shared library /usr/lib/python2.7/lib-dynload/_collections.so: Exec format error
> Traceback (most recent call last):
>   File "/app/medusa/start.py", line 8, in <module>
>     from medusa.__main__ import main
>   File "/app/medusa/medusa/__init__.py", line 20, in <module>
>     from medusa.app import app
>   File "/app/medusa/medusa/app.py", line 8, in <module>
>     from threading import Lock
>   File "/usr/lib/python2.7/threading.py", line 13, in <module>
>     from collections import deque as _deque
>   File "/usr/lib/python2.7/collections.py", line 20, in <module>
>     from _collections import deque, defaultdict
> ImportError: Error loading shared library /usr/lib/python2.7/lib-dynload/_collections.so: Exec format error
> Traceback (most recent call last):
>   File "/app/medusa/start.py", line 8, in <module>
>     from medusa.__main__ import main
>   File "/app/medusa/medusa/__init__.py", line 20, in <module>
>     from medusa.app import app
>   File "/app/medusa/medusa/app.py", line 8, in <module>
>     from threading import Lock
>   File "/usr/lib/python2.7/threading.py", line 13, in <module>
>     from collections import deque as _deque
>   File "/usr/lib/python2.7/collections.py", line 20, in <module>
>     from _collections import deque, defaultdict
```

docker-compose
```
   medusa:
     container_name: medusa
     image: linuxserver/medusa 
     ports:
       - 8081:8081/tcp
     environment:
       - TZ=Europe/Brussels
       - PUID=0
       - PGID=0
     volumes:
       - /mnt/usb_2/downloads:/downloads
       - /etc/localtime:/etc/localtime
       - /mnt/usb_2/Video/TV:/mnt/usb_2/Video/TV
       - /opt/docker/medusa/conf:/config
```

**Comment by thelamer** [comment]
What hardware ? Our images no longer support pi 1s and zeros , armv7 and up only. 

The arm image passed our basic internal CI https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/medusa/latest/index.html

**Comment by elRadix** [comment]
RPi 3 Model B (armv7l)


Linux 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

**Comment by elRadix** [comment]
I get this error also on tautulli etc
linuxserver/tautulli:arm32v7-latest or with linuxserver/tautulli:latest	
```

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/app/tautulli/PlexPy.py", line 24, in <module>
    from Tautulli import main
  File "/app/tautulli/Tautulli.py", line 30, in <module>
    import argparse
  File "/app/tautulli/lib/argparse.py", line 86, in <module>
    import collections as _collections
  File "/usr/lib/python2.7/collections.py", line 20, in <module>
    from _collections import deque, defaultdict
ImportError: Error loading shared library /usr/lib/python2.7/lib-dynload/_collections.so: Exec format error
```

**Comment by j0nnymoe** [comment]
Don't run as root.

**Comment by sparklyballs** [comment]
exec format error is usually a signal that you're using the wrong image for your architecture, possibly somehow docker is not picking up the arch correctly 

try pulling the armhf specific image as outlined here

https://github.com/linuxserver/docker-medusa#supported-architectures

**Comment by thelamer** [comment]
Yeah pi3 is arm64 not armv7, you need aarch64 docker

**Comment by sparklyballs** [comment]
depends on the os used whether the pi3 is arm64 or armhf

raspbian for  instance runs it as armhf

**Comment by elRadix** [comment]
Just test with this image: linuxserver/medusa:arm32v7-latest

armhf  = arm32v7-latest

tested with root and non root user, still the same issue mentioned above

**Comment by sparklyballs** [comment]
```
pi@Docker-Slave-PI-0:~ $ docker run --rm=true -it linuxserver/medusa:arm64v8-latest bash
Unable to find image 'linuxserver/medusa:arm64v8-latest' locally
arm64v8-latest: Pulling from linuxserver/medusa
00836c94782d: Pull complete 
b2abf718a4e7: Pull complete 
b3670d87f62a: Pull complete 
773bec364303: Pull complete 
42fea2a8aee5: Pull complete 
98f7a8d8f0ea: Pull complete 
Digest: sha256:f5a6305fff673c3ace99f598fa775073c50cf2ce220a5625f773b185e4904fd8
Status: Downloaded newer image for linuxserver/medusa:arm64v8-latest
standard_init_linux.go:207: exec user process caused "exec format error"
```

ran on my pi3 using raspbian which reports itself as

```
pi@Docker-Slave-PI-0:~ $ uname -m
armv7l
```

**Comment by sparklyballs** [comment]
with the armhf specific image on the same machine.....

https://pastebin.com/CDWeKGpY

**Comment by thelamer** [comment]
@elRadix did @sparklyballs reduced complexity test command work for you ? 
```docker run --rm=true -it linuxserver/medusa:arm32v7-latest```
If that works you know it is something in your settings.

**Comment by elRadix** [comment]
@thelamer tried the above command, still the same error as posted in the first post.

**Comment by elRadix** [comment]
issue resolved with the latest medusa image update.
did not change anything to my system
