### ISSUE TITLE
[BUG] Incorrect permissions for /app

### ISSUE THREAD

**Issue by j-aub** [linuxserver/docker-medusa#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Medusa connects to anidb, it tries to write to /app/medusa/Session.cfg. But since /app/medusa is owned by root the write fails.

The regression seems to have been introduced in this commit: https://github.com/linuxserver/docker-medusa/commit/c1321ed98c18fd179b65007fb8533268af296baa

![image](https://user-images.githubusercontent.com/37088847/230822982-450ed7cd-c755-475d-9dc2-d6255bab5063.png)

The /app dir no longer gets chowned to abc:abc. This is /app/medusa with linuxserver/medusa:1.0.13:

```
root@2fef5c9f927d:/# ls -al /app/medusa/
total 296
drwxr-xr-x 13 root root   4096 Apr  6 11:01 .
drwxr-xr-x  1 abc  users  4096 Apr  9 23:32 ..
drwxrwxr-x  2 root root   4096 Apr  6 11:01 .build
-rw-rw-r--  1 root root   4576 Mar 22 14:17 .codecov.yml
-rw-rw-r--  1 root root    302 Mar 22 14:17 .dockerignore
-rw-rw-r--  1 root root    464 Mar 22 14:17 .editorconfig
-rw-rw-r--  1 root root   1432 Mar 22 14:17 .gitattributes
drwxrwxr-x  4 root root   4096 Apr  6 11:01 .github
-rw-rw-r--  1 root root   1162 Mar 22 14:17 .gitignore
-rw-rw-r--  1 root root     79 Mar 22 14:17 .yarnrc
-rw-rw-r--  1 root root  55837 Mar 22 14:17 CHANGELOG.md
-rw-rw-r--  1 root root   2648 Mar 22 14:17 CONTRIBUTING.md
-rw-rw-r--  1 root root  35132 Mar 22 14:17 COPYING.txt
-rw-rw-r--  1 root root   1514 Mar 22 14:17 Dockerfile
-rw-rw-r--  1 root root    302 Mar 22 14:17 MANIFEST.in
-rwxrwxr-x  1 root root    200 Mar 22 14:17 SickBeard.py
drwxrwxr-x  2 root root   4096 Apr  6 11:01 dredd
drwxrwxr-x 62 root root   4096 Apr  6 11:01 ext
drwxrwxr-x  2 root root   4096 Apr  6 11:01 hooks
drwxrwxr-x 10 root root   4096 Apr  6 11:01 lib
drwxrwxr-x 30 root root   4096 Apr  6 11:01 medusa
-rw-rw-r--  1 root root    390 Mar 22 14:17 package.json
-rw-rw-r--  1 root root   6844 Mar 22 14:17 readme.md
-rw-rw-r--  1 root root   1066 Mar 22 14:17 renovate.json
-rw-rw-r--  1 root root   1046 Mar 22 14:17 requirements.txt
drwxrwxr-x  2 root root   4096 Apr  6 11:01 runscripts
-rw-rw-r--  1 root root   9999 Mar 22 14:17 setup.cfg
-rw-rw-r--  1 root root   3104 Mar 22 14:17 setup.py
-rwxrwxr-x  1 root root    180 Mar 22 14:17 start.py
-rw-rw-r--  1 root root    340 Mar 22 14:17 test_requirements.txt
drwxrwxr-x  9 root root   4096 Apr  6 11:01 tests
drwxrwxr-x  4 root root   4096 Apr  6 11:01 themes
drwxrwxr-x  3 root root   4096 Apr  6 11:01 themes-default
-rw-rw-r--  1 root root    341 Mar 22 14:17 tox.ini
-rw-rw-r--  1 root root  59571 Mar 22 14:17 yarn.lock
```

This is where Session.cfg comes from on Medusa's end: https://github.com/pymedusa/Medusa/blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/ext/adba/__init__.py#L94

### Expected Behavior

The /app directory should have the correct permissions so that Medusa is able to use it.

### Steps To Reproduce

1. Have Medusa connect to anidb

### Environment

```markdown
- OS: Debian 11, linuxserver/medusa:1.0.13
- How docker service was installed: package manager
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
2023-04-09 23:23:46 WARNING  APIv2-Thread_6 :: [] anidb exception msg: PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "/app/medusa/medusa/helpers/anidb.py", line 40, in set_up_anidb_connection
    app.ADBA_CONNECTION.auth(app.ANIDB_USERNAME, app.ANIDB_PASSWORD)
  File "/app/medusa/ext/adba/__init__.py", line 282, in auth
    with open(self.SessionFile, 'w') as configfile:
PermissionError: [Errno 13] Permission denied: '/app/medusa/Session.cfg'
```

**Comment by thespad** [comment]
Please can you test `lspipepr/medusa:v1.0.13-pkg-04fb8cf2-pr-49` and see if it resolves the issue for you.

**Comment by j-aub** [comment]
Hi, that looks to have fixed it. Thanks
